import os
import datetime

def generate_study_notes(topic: str, content: str) -> str:
    """
    Generates academic study notes locally on the computer.
    Saves the notes to an 'Archives/StudyNotes' directory on the Desktop.
    """
    try:
        # Get Desktop path for Windows
        desktop = os.path.join(os.environ["USERPROFILE"], "Desktop")
        archives_dir = os.path.join(desktop, "ADITYA_Archives", "StudyNotes")
        
        # Create directory if it doesn't exist
        os.makedirs(archives_dir, exist_ok=True)
        
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        safe_topic = "".join([c for c in topic if c.isalpha() or c.isdigit() or c==' ']).rstrip()
        filename = f"{safe_topic}_{timestamp}.md"
        filepath = os.path.join(archives_dir, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(f"# {topic}\n\n")
            f.write(f"*Generated by ADITYA Cognitive OS on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
            f.write("---\n\n")
            f.write(content)
            
        return f"Study notes for '{topic}' successfully saved to {filepath}"
    except Exception as e:
        return f"Failed to generate study notes: {str(e)}"
