name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to ADITYA OS! Thank you for raising this issue. A maintainer will review it shortly.'
        pr-message: 'Thank you for your first Pull Request! We appreciate your contribution to ADITYA OS. We will review your changes as soon as possible.'
