name: Pull Request Size Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-size:
    name: Check Modification Size
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Assign Size Labels
      uses: pascalgn/size-label-action@v0.5.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sizes: |
          {"0": "size/XS", "50": "size/S", "250": "size/M", "1000": "size/L", "5000": "size/XL"}
